### ISSUE TITLE
Append VIVA TV RUSSIA

### ISSUE THREAD

**Issue by vasilyevmichail** [Forst/iptv#7]
VIVA TV RUSSIA 

Music channel

Logo: https://i.imgur.com/qCLICfC.jpg
URL: https://hls.myvideocontent.ru/hls2/vivarussia/index.m3u8

Free channel

**Comment by Forst** [comment]
Плейлист в данном репозитории предназначен только для телеканалов, вещаемых через мультикаст в сети Wifire (ex. Netbynet). Вы предоставили ссылку на сторонний HLS-поток.
